---
- name: ansible-playbook to configure network objects to Panorama
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Import file containing the login details and source file
    include_vars:
      file: secrets.yaml

  - name: Import Source file and convert to json
    xls_to_facts:
      src: variables/{{ source }}.xlsx
    register: configxls

  # - name: Populate Network Objects to be configured to yaml file
  #   template:
  #     src: templates/networkadd.j2
  #     dest: variables/networkaddress-variable.yaml
  #   tags: template, networkaddress

  # - name: Populate Network Group Objects to be configured to yaml file
  #   template:
  #     src: templates/networkgroup.j2
  #     dest: variables/networkgroup-variable.yaml
  #   tags: template, networkgroup

  - name: Import Network Objects variables file
    include_vars:
      file: variables/networkaddress-variable.yaml
    tags: import, networkaddress
  
  - name: Import Network Group Objects variables file
    include_vars:
      file: variables/networkgroup-variable.yaml
    tags: import, networkgroups

  # - name: Configure network addresses
  #   include_tasks: tasks/Network-Objects/address.yaml
  #   when:
  #     - networkadd != none
  #     - item.addressgroupip.find('-') == -1
  #   with_items: "{{ networkadd }}"
  #   tags: configure, networkaddress

  # - name: Configure network ranges
  #   include_tasks: tasks/Network-Objects/address-range.yaml
  #   when:
  #   - networkadd != None
  #   - item.addressgroupip.find('-') != -1
  #   with_items: "{{ networkadd }}"
  #   tags: configure, networkaddress

  - name: Configure network groups
    include_tasks: tasks/Network-Objects/groups.yaml
    when: networkgroup != none
    with_items: "{{ networkgroup }}"
    tags: configure, networkgroups
...



