---
- name: ansible-playbook to configure security policy on panorama
  hosts: localhost
  gather_facts: true
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Import file containing the login details and source file
    include_vars:
      file: secrets.yaml

  - name: Import Source file and convert to json
    xls_to_facts:
      src: variables/{{ source }}.xlsx
    register: configxls
  
  - name: populate pre-rule to be configured to yaml file
    template: 
      src: templates/securitypolicy.j2
      dest: variables/securitypolicy-variable.yaml

  - name: import pre-rules variable file
    include_vars:
      file: variables/securitypolicy-variable.yaml

  - name: add security policy on panorama
    include_tasks: tasks/Security-Policies/add-securitypolicy.yaml
    when: 
      - securitypolicy != none
      - item.operation == "add"
    with_items: "{{ securitypolicy }}"
    tags: configure, prerule

  - name: update security policy on panorama
    include_tasks: tasks/Security-Policies/update-securitypolicy.yaml
    when: 
      - securitypolicy != none
      - item.operation == "update"
    with_items: "{{ securitypolicy }}"
...