---
- name:
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    provider:
      ip_address: "192.168.1.250"
      username: "admin"
      password: "admin"

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  
    - name: check
      panos_security_rule_facts:
        provider: "{{ provider }}"
        device_group: "dg_au_dc_innerfw"
        rulebase: "post-rulebase"
      register: result
    
    - debug:
        msg: "{{ result.rules }}"

 