---
- name: ansible-playbook to configure security policy post-rules on panorama
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Import file containing the login details and source file
    include_vars:
      file: secrets.yaml

  - name: Import Source file and convert to json
    xls_to_facts:
      src: variables/{{ source }}.xlsx
    register: configxls

  - name: populate port-rule to be configured to yaml file
    template:
      src: templates/securitypolicy-postrule.j2
      dest: variables/securitypolicy-postrule-variable.yaml
    tags: template, postrule

  - name: import post-rule variable file
    include_vars:
      file: variables/securitypolicy-postrule-variable.yaml
    tags: import, postrule
  
  - name: configure post-rules on panorama
    include_tasks: tasks/securitypolicy-postrule-task.yaml
    when: policy != none
    with_items: "{{ policy }}"
    tags: configure, postrule
...