- name: Import's service-variables yaml file
  include_vars:
    file: variables/servicegroups-variable.yaml

- name: create service Objects
  panos_object:
    ip_address : "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    servicegroup: "{{ item.name }}"
    services: "{{ item.members }}"
    description: " Added by ansible "
    devicegroup: "Test"
    operation: "add"
  with_items: "{{ servicesgroups }}"
