- name: Import the variables necessart to add security policies
  include_vars:
    file: variables/policy.yaml

- name: create security policy
  panos_security_rule:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    operation: "add"
    rule_name: "{{ item.name }}"
    description: "{{ item.description }}"
    source_zone: "{{ item.sourcezone }}"
    source_ip: "{{ item.sourceip }}"
    destination_zone: "{{ item.destinationzone }}"
    destination_ip: "{{ item.destinationip }}"
    service: "{{ item.service }}"
    application: "{{ item.application }}"
    action: "allow"
    tag_name: "{{ item.tag_name }}"
    devicegroup: "{{ devicegroups }}"
    rule_type: "{{ rule_type }}"
    log_start: "{{ log_start }}"
    log_end: "{{ log_end }}"
    group_profile: "{{ group_profile }}"
    is_post_rule: true
    position: "{{ position }}"
    # location: "{{ policy_position.location }}"
    # existing_rule: "{{ policy_position.existing_rule }}"
    commit: "False"
  with_items: "{{ policy }}"
