- name: Include the networkgroup.yaml file
  include_vars:
    file: variables/networkgroup-variable.yaml


- name : Create network Object Groups
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressgroup: "{{ item.addressgroupname }}"
    static_value: "{{ item.addressgroupip }}"
    description: " pushed through Ansibel"
    devicegroup: "Test"
    operation: "add"
  with_items: "{{ networkgroup }}"
  ignore_errors: true