- name: Import the variables necessart to add security policies
  include_vars:
    file: variables/securitypolicy-postrule-variable.yaml

- name: create security policy - post rule
  panos_security_rule_post:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    operation: "{{ item.Operation }}"
    rule_name: "{{ item.name }}"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    tag_name: "{{ item.tag_name }}"
    rule_type: "{{ item.rule_type }}"
    source_zone: "{{ item.source_zone }}"
    source_ip: "{{ item.source_ip }}"
    source_user: "{{ item.source_user }}"
    hip_profiles: "{{ item.hip_profiles }}"
    destination_zone: "{{ item.destination_zone }}"
    destination_ip: "{{ item.destination_ip }}"
    url_filtering: "{{ item.url_filtering }}"
    service: "{{ item.service }}"
    application: "{{ item.application }}"
    action: "{{ item.action }}"
    log_start: "{{ item.log_start }}"
    log_end: "{{ item.log_end }}"
    group_profile: "{{ item.group_profile }}"
    is_post_rule: True
    position: "{{ item.position }}"
    commit: "False"
  when: policy  != None
  with_items: "{{ policy }}"
