- name: Import the variables necessart to add security policies - Pre Rules
  include_vars:
    file: variables/securitypolicy-prerule-variable.yaml

- name: Configure Pre-rules
  panos_security_rule:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: present
    rule_name: "{{ item.name }}"
    description: "{{ item.description }}"
    device_group: "{{ item.devicegroup }}"
    tag_name: "{{ item.tag_name }}"
    rule_type: "{{ item.rule_type }}"
    source_zone: "{{ item.source_zone }}"
    source_ip: "{{ item.source_ip }}"
    source_user: "{{ item.source_user }}"
    hip_profiles: "{{ item.hip_profiles }}"
    destination_zone: "{{ item.destination_zone }}"
    destination_ip: "{{ item.destination_ip }}"
    category: "{{ item.category }}"
    service: "{{ item.service }}"
    application: "{{ item.application }}"
    action: "{{ item.action }}"
    group_profile: "{{ item.group_profile }}"
    log_start: "{{ item.log_start }}"
    log_end: "{{ item.log_end }}"
    log_setting: "{{ item.log_setting }}"
    location: "{{ item.location }}"
    existing_rule: "{{ item.existing_rule }}"
  when: prerule != None
  with_items: "{{ prerule }}"
  