- name : Create network Object Groups
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressgroup: "{{ item.addressgroupname }}"
    static_value: "{{ item.addressgroupip }}"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  ignore_errors: true