- name: Configure Network address when it is not a range
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressobject: "{{ item.addressgroupname }}"
    address: "{{ item.addressgroupip }}"
    address_type: "ip-netmask"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  when: item.addressgroupip.find('-') == -1
  with_items: "{{ networkadd }}"
  ignore_errors: true

- name: Configure Network address when it is a range
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressobject: "{{ item.addressgroupname }}"
    address: "{{ item.addressgroupip }}"
    address_type: "ip-range"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  when: item.addressgroupip.find('-') != -1
  with_items: "{{ networkadd }}"
  ignore_errors: true