- name: create service Objects
  panos_object:
    ip_address : "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    servicegroup: "{{ item.name }}"
    services: "{{ item.members }}"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  register: result
  ignore_errors: true

- name: Log when failed
  lineinfile:
    path: logs/servicegroups-log.csv
    create: yes
    line: "Failed, {{ result.msg }}"
  when: result.failed == true

- name: Log when successful
  lineinfile:
    path: logs/servicegroups-log.csv
    create: yes
    line: "Successful, {{ result.msg }}"
  when: result.failed == false


