- name: Configure Network address when it is a range
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressobject: "{{ item.addressgroupname }}"
    address: "{{ item.addressgroupip }}"
    address_type: "ip-range"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  ignore_errors: true
  register: result

- name: Log the result when Failed
  lineinfile:
    path: logs/networkaddresses.csv
    create: yes
    line: "Failed, {{ result.msg }}"
  when: result.failed == true

- name: Log the result when Successful
  lineinfile:
    path: logs/networkaddresses.csv
    create: yes
    line: "Successful, {{ result.msg }}"
  when: result.failed == false