- name: Configure Network address when it is not a range
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressobject: "{{ item.addressgroupname }}"
    address: "{{ item.addressgroupip }}"
    address_type: "ip-netmask"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  ignore_errors: true
  register: result

- name: add Tag if object was created
  panos_type_cmd:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    xpath: |
      /config/devices/entry[@name='localhost.localdomain']/device-group/
      entry[@name='{{ item.devicegroup }}']/address/
      entry[@name='{{ item.addressgroupname }}']/tag
    element: |
      <member>{{ item.tags }}</member>
  when: result.failed == false
  ignore_errors: true


- name: Log the result when failed
  lineinfile:
    path: logs/networkaddresses-log.csv
    create: yes
    line: "{{ item.addressgroupname}}, Failed, {{ result.msg }}"
  when: result.failed == true

- name: Log the result when Successful
  lineinfile:
    path: logs/networkaddresses-log.csv
    create: yes
    line: "{{ item.addressgroupname}}, Successful, {{ result.msg }}"
  when: result.failed == false

