- name : Create network Object Groups
  panos_object:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
    addressgroup: "{{ item.addressgroupname }}"
    static_value: "{{ item.addressgroupip }}"
    description: "{{ item.description }}"
    devicegroup: "{{ item.devicegroup }}"
    operation: "{{ item.operation }}"
  ignore_errors: true
  register: result

- name: Log when failed
  lineinfile:
    path: logs/networkgroups-log.csv
    create: yes
    line: "Failed, {{ result.msg }}"
  when: result.failed == true

- name: Log when successful
  lineinfile:
    path: logs/networkgroups-log.csv
    create: yes
    line: "Successful, {{ result.msg }}"
  when: result.failed == false